# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
pr:
  autoCancel: true
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    clean: true
    path: src
  - task: CmdLine@2
    inputs:
      script: |
        ls
        ls src/