# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    ls
  displayName: 'List dir'

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'DBAG Sonar'
    scannerMode: 'MSBuild'
    projectKey: 'sap.crm-devopsdemo'
    projectName: 'sap.crm-devopsdemo'

- task: SonarQubeAnalyze@4

- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'
    
- task: Npm@1
  inputs:
    command: 'install'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'

- script: |
    ls dist/
  displayName: 'List dir'