# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
pr:
  autoCancel: true
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'
 
steps:

- script: dir
  workingDirectory: $(Agent.BuildDirectory)/src
  displayName: Create src

- task: CmdLine@2
  inputs:
    script: |
      ls

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: CmdLine@2
  inputs:
    script: |
      ls
      docker run --rm -v "${PWD}":$(Agent.BuildDirectory)/src -it ppiper/mta-archive-builder:latest mtaBuild --mtar dummy.mtar --build-target NEO build