# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: 'SAPUI5' 

steps: 
  
  - task: Docker@2
    inputs:
      containerRegistry: 'FVS Docker`'
      command: 'login'
  - task: CmdLine@2
    inputs:
      script: docker pull tomcat
  

